---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github action updates"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip updates"
