- id: mypy-linter
  name: mypy
  language: python
  files: \.py$
  types: [python]
  entry: python -m pre_commit_hooks.mypy
  additional_dependencies: ["mypy"]
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
  require_serial: true

- id: shellcheck-linter
  name: shellcheck
  description: Runs shellcheck on all the shell scripts
  language: python
  files: \.(sh|bash|zsh)$
  types: [shell]
  entry: python -m pre_commit_hooks.shellcheck
  additional_dependencies: ["shellcheck-py"]
  stages: [pre-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0
  require_serial: true
